- hosts: localhost
  
  vars: 
    - container_name: ecomm_docker
    - container_image: ecommv2
    - dock_key_url: https://download.docker.com/linux/ubuntu/gpg
    - dock_repo_url: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
  
  tasks:
     
  - name: Install dependancies
    apt:
      name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    become: yes
      
  - name: Add Docker GPG apt key
    apt_key:
      url: "{{ dock_key_url }}"
      state: present
    become: yes
      
  - name: Add Docker repository
    apt_repository:
      repo: "{{ dock_repo_url }}"
      state: present
    become: yes
     
  - name: Install docker
    apt:
      name: docker-ce
      update_cache: yes
      state: present
    become: yes
    
  - name: Install pip
    apt:
      name: python3-pip
      update_cache: yes
      cache_valid_time: 600
      state: present
    become: yes 
    
  - name: Install docker Module for Python
    pip:
      name: docker
      state: present
    become: yes
